Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 130

Metrics/AbcSize:
  Max: 50
